name: Create ephemeral GCE VM

on:
  workflow_call:
    inputs:
      task:
        type: string
        required: false
        default: "default"
    secrets:
      gcp_credentials:
        required: true
      runner_token:
        required: true
    outputs:
      label:
        value: ${{ jobs.run.outputs.label }}
      machine-zone:
        value: ${{ jobs.run.outputs.machine-zone }}

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
      machine-zone: ${{ steps.create-runner.outputs.machine-zone }}
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - id: gcloud-auth
        name: gcloud auth activate-service-account
        shell: bash
        run: |
          gcloud auth activate-service-account --key-file ${{ steps.auth.outputs.credentials_file_path }}
      - id: create-runner
        uses: gitpod-io/gce-github-runner@secrets
        with:
          runner_token: ${{ secrets.runner_token }}
          task: ${{ inputs.task }}

